# Google Cloud Build Configuration
# Optimized for production deployment with cost-effective settings

steps:
  # Step 1: Build the production Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - build
      - --no-cache
      - --file
      - Dockerfile
      - --build-arg
      - VITE_SUPABASE_URL=https://lydxcnvyzqaumfmfktor.supabase.co
      - --build-arg
      - VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5ZHhjbnZ5enFhdW1mbWZrdG9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDA2MTYsImV4cCI6MjA3Mzc3NjYxNn0.k6KTuE60TCOQi9YK4CdEZPmHYVc6__13qtVqa8lSn_o
      - --build-arg
      - VITE_API_BASE_URL=https://medai-506044864836.europe-west1.run.app
      - --tag
      - gcr.io/$PROJECT_ID/medical-assistant:latest
      - .      git add Dockerfile
      git commit -m "Fix: Move ARG declarations to top of Docker stage before they're used"
      git push
    timeout: '1200s'

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args: [
      'push', 'gcr.io/$PROJECT_ID/medical-assistant:latest'
    ]
    waitFor: ['build-image']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-service'
    args: [
      'run', 'deploy', 'medical-assistant',
      '--image', 'gcr.io/$PROJECT_ID/medical-assistant:latest',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '${_MEMORY}',
      '--cpu', '${_CPU}',
      '--concurrency', '${_CONCURRENCY}',
      '--max-instances', '${_MAX_INSTANCES}',
      '--min-instances', '${_MIN_INSTANCES}',
      '--cpu-throttling',
      '--execution-environment', 'gen2',
      '--timeout', '${_TIMEOUT}',
      '--startup-cpu-boost',
      '--set-env-vars', 'ENVIRONMENT=production,PORT=8080,HOST=0.0.0.0,LOG_LEVEL=INFO,ENABLE_RATE_LIMITING=true,RATE_LIMIT_PER_MINUTE=10,RATE_LIMIT_PER_HOUR=50,RATE_LIMIT_BLOCK_HOURS=1,CORS_ALLOW_CREDENTIALS=true,ENABLE_INPUT_VALIDATION=true,MAX_MESSAGE_LENGTH=1000,LOG_VALIDATION_FAILURES=true,SUSPICIOUS_PATTERN_THRESHOLD=10',
      '--set-secrets', 'GOOGLE_API_KEY=GOOGLE_API_KEY:latest',
      '--set-secrets', 'SUPABASE_URL=SUPABASE_URL:latest',
      '--set-secrets', 'SUPABASE_SERVICE_ROLE_KEY=SUPABASE_SERVICE_ROLE_KEY:latest'
    ]
    waitFor: ['push-image']

  # Step 4: Verify deployment health
  - name: 'gcr.io/cloud-builders/curl'
    id: 'health-check'
    args: [
      '-f',
      '--retry', '5',
      '--retry-delay', '10',
      '--retry-max-time', '60',
      'https://medical-assistant-${_REGION}-${PROJECT_ID}.a.run.app/health'
    ]
    waitFor: ['deploy-service']

# Substitution variables with defaults
substitutions:
  _REGION: 'us-central1'        # Cheapest region
  _MEMORY: '1Gi'                # Minimum for AI workload
  _CPU: '1'                     # 1 vCPU
  _CONCURRENCY: '80'            # High concurrency for cost efficiency
  _MAX_INSTANCES: '10'          # Reasonable limit
  _MIN_INSTANCES: '0'           # Scale to zero for cost savings
  _TIMEOUT: '300'               # 5 minute timeout
  # Frontend build-time variables (embedded into static files)
  _VITE_SUPABASE_URL: 'https://lydxcnvyzqaumfmfktor.supabase.co'
  _VITE_SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5ZHhjbnZ5enFhdW1mbWZrdG9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDA2MTYsImV4cCI6MjA3Mzc3NjYxNn0.k6KTuE60TCOQi9YK4CdEZPmHYVc6__13qtVqa8lSn_o'
  _VITE_API_BASE_URL: 'https://medai-506044864836.europe-west1.run.app'

# Build configuration for cost optimization
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_STANDARD_2'  # Cost-effective machine type
  diskSizeGb: 50                # Minimal disk size
  substitutionOption: 'ALLOW_LOOSE'

# Overall timeout
timeout: '1800s'  # 30 minutes maximum

# Tags for organization
tags: ['medical-assistant', 'production', 'cloud-run']