# Google Cloud Build Configuration
# Optimized for production deployment with cost-effective settings

steps:
  # Step 1: Build the production Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args: [
      'build',
      '--file', 'Dockerfile',
      '--cache-from', 'gcr.io/$PROJECT_ID/medical-assistant:latest',
      '--tag', 'gcr.io/$PROJECT_ID/medical-assistant:$COMMIT_SHA',
      '--tag', 'gcr.io/$PROJECT_ID/medical-assistant:latest',
      '.'
    ]
    timeout: '1200s'

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args: [
      'push', 'gcr.io/$PROJECT_ID/medical-assistant:latest'
    ]
    waitFor: ['build-image']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-service'
    args: [
      'run', 'deploy', 'medical-assistant',
      '--image', 'gcr.io/$PROJECT_ID/medical-assistant:latest',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '${_MEMORY}',
      '--cpu', '${_CPU}',
      '--concurrency', '${_CONCURRENCY}',
      '--max-instances', '${_MAX_INSTANCES}',
      '--min-instances', '${_MIN_INSTANCES}',
      '--cpu-throttling',
      '--execution-environment', 'gen2',
      '--timeout', '${_TIMEOUT}',
      '--set-env-vars', 'ENVIRONMENT=production,PORT=8080',
      '--set-secrets', 'GOOGLE_API_KEY=medical-assistant-secrets:latest:google-api-key',
      '--set-secrets', 'SUPABASE_URL=medical-assistant-secrets:latest:supabase-url',
      '--set-secrets', 'SUPABASE_ANON_KEY=medical-assistant-secrets:latest:supabase-anon-key',
      '--set-secrets', 'SUPABASE_SERVICE_ROLE_KEY=medical-assistant-secrets:latest:supabase-service-role-key'
    ]
    waitFor: ['push-image']

  # Step 4: Verify deployment health
  - name: 'gcr.io/cloud-builders/curl'
    id: 'health-check'
    args: [
      '-f',
      '--retry', '5',
      '--retry-delay', '10',
      '--retry-max-time', '60',
      'https://medical-assistant-${_REGION}-${PROJECT_ID}.a.run.app/health'
    ]
    waitFor: ['deploy-service']

# Substitution variables with defaults
substitutions:
  _REGION: 'us-central1'        # Cheapest region
  _MEMORY: '1Gi'                # Minimum for AI workload
  _CPU: '1'                     # 1 vCPU
  _CONCURRENCY: '80'            # High concurrency for cost efficiency
  _MAX_INSTANCES: '10'          # Reasonable limit
  _MIN_INSTANCES: '0'           # Scale to zero for cost savings
  _TIMEOUT: '300'               # 5 minute timeout

# Build configuration for cost optimization
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_STANDARD_2'  # Cost-effective machine type
  diskSizeGb: 50                # Minimal disk size
  substitutionOption: 'ALLOW_LOOSE'

# Overall timeout
timeout: '1800s'  # 30 minutes maximum

# Tags for organization
tags: ['medical-assistant', 'production', 'cloud-run']